on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      security-events: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # - name: install tfsec
    #   run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      
   
    # - name: Upload artifact 2
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: results.json
    #     path: results.json
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: 20

    - name: tfsec
      uses: tfsec/tfsec-sarif-action@master
      with:
        sarif_file: tfsec.sarif         

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: tfsec.sarif

    - name: Analyze SARIF results
      uses: github/codeql-action/analyze-sarif@v3
      with:
        sarif_file: tfsec.sarif

    - name: Test with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        framework: terraform     

    - name: Generate TF Docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
    

   
    - name: Install dependencies
      run: npm ci
      env:
        CI: true

    - name: Semantic release
      run: npx semantic-release    